import { CheckCircle2, CircleX } from 'lucide-react';
import { useEffect, useState } from 'react';
import { MathText } from '../components/MathText';
import type { McqAnswer, McqQuestion } from '../domain/types';
export function McqCard({ question, answer, onAnswer }: { question: McqQuestion; answer?: McqAnswer; onAnswer: (answer: McqAnswer) => void }) {
  const [selected, setSelected] = useState<number | null>(answer?.selectedIndex ?? null); useEffect(() => setSelected(answer?.selectedIndex ?? null), [question.id, answer]); const checked = Boolean(answer);
  const submit = () => { if (selected === null) return; onAnswer({ kind: 'mcq', selectedIndex: selected, correct: selected === question.correctIndex, answeredAt: new Date().toISOString() }); };
  return <section aria-labelledby="question-title"><h1 id="question-title" className="question-text"><MathText>{question.question}</MathText></h1><fieldset className="options" disabled={checked}><legend className="sr-only">Выберите один вариант</legend>{question.options.map((option, i) => { const state = checked ? i === question.correctIndex ? 'correct' : i === selected ? 'wrong' : '' : i === selected ? 'selected' : ''; return <label className={`option ${state}`} key={i}><input type="radio" name={`answer-${question.id}`} checked={selected === i} onChange={() => setSelected(i)}/><span className="option-key">{String.fromCharCode(65 + i)}</span><span><MathText>{option}</MathText></span>{checked && i === question.correctIndex && <CheckCircle2 aria-label="Правильный ответ"/>}{checked && i === selected && i !== question.correctIndex && <CircleX aria-label="Неправильный ответ"/>}</label>; })}</fieldset>
    {!checked ? <button className="button primary full" disabled={selected === null} onClick={submit}>Проверить ответ</button> : <div className={`feedback ${answer?.correct ? 'success' : 'danger'}`} aria-live="polite"><h2>{answer?.correct ? <><CheckCircle2/> Верно</> : <><CircleX/> Неверно</>}</h2><p><MathText>{question.explanation}</MathText></p>{question.rationales?.[answer!.selectedIndex] && <p><strong>О выбранном варианте:</strong> <MathText>{question.rationales[answer!.selectedIndex]}</MathText></p>} {question.rationales && <details><summary>Пояснения ко всем вариантам</summary><ol>{question.rationales.map((r, i) => <li key={i}><MathText>{r}</MathText></li>)}</ol></details>}{question.sourceQuote && <details><summary>Фрагмент источника</summary><blockquote><MathText>{question.sourceQuote}</MathText></blockquote></details>}</div>}
  </section>;
}
