import { Eye, ThumbsDown, ThumbsUp } from 'lucide-react';
import { useEffect, useState } from 'react';
import { MathText } from '../components/MathText';
import type { OpenAnswer, OpenQuestion, OpenRating } from '../domain/types';
const ratings: { value: OpenRating; label: string }[] = [{ value: 'correct', label: 'Ответил правильно' }, { value: 'partial', label: 'Ответил частично' }, { value: 'incorrect', label: 'Не ответил / неправильно' }];
export function OpenCard({ question, answer, draft, showAnswerPlan = false, onDraft, onAnswer, onRate }: { question: OpenQuestion; answer?: OpenAnswer; draft: string; showAnswerPlan?: boolean; onDraft: (v: string) => void; onAnswer: (a: OpenAnswer) => void; onRate: (r: OpenRating) => void }) {
  const [text, setText] = useState(answer?.text ?? draft); useEffect(() => setText(answer?.text ?? draft), [question.id, answer, draft]); const checked = Boolean(answer);
  const reveal = (skipped: boolean) => onAnswer({ kind: 'open', text: skipped ? '' : text.trim(), skipped, answeredAt: new Date().toISOString() });
  const plan = question.answerPlan ?? question.keyPoints;
  return <section aria-labelledby="question-title"><h1 id="question-title" className="question-text"><MathText>{question.question}</MathText></h1>{showAnswerPlan && !checked && <aside className="answer-plan"><h2>План ответа</h2><p>Идите по пунктам — полного литературного ответа не требуется.</p><ol>{plan.map((point) => <li key={point}><MathText>{point}</MathText></li>)}</ol></aside>}{!checked ? <><label className="field-label" htmlFor="open-answer">Ваш ответ</label><textarea id="open-answer" rows={8} value={text} placeholder="Сформулируйте ответ своими словами…" onChange={(e) => { setText(e.target.value); onDraft(e.target.value); }}/><div className="button-row"><button className="button secondary" onClick={() => reveal(true)}><Eye/> Не знаю — показать</button><button className="button primary" disabled={!text.trim()} onClick={() => reveal(false)}>Сверить с эталоном</button></div></> : <div className="answer-comparison" aria-live="polite"><div className="your-answer"><h2>Ваш ответ</h2><p>{answer?.text || 'Ответ пропущен'}</p></div><div className="model-answer"><h2>Эталонный ответ</h2><p><MathText>{question.modelAnswer}</MathText></p><h3>Ключевые пункты</h3><ul>{question.keyPoints.map((point) => <li key={point}><MathText>{point}</MathText></li>)}</ul>{question.sourceQuote && <details><summary>Фрагмент источника</summary><blockquote><MathText>{question.sourceQuote}</MathText></blockquote></details>}</div><fieldset className="rating"><legend>Как вы оцениваете свой ответ?</legend>{ratings.map((r) => <button key={r.value} className={`button rating-${r.value} ${answer?.rating === r.value ? 'chosen' : ''}`} onClick={() => onRate(r.value)}>{r.value === 'correct' ? <ThumbsUp/> : r.value === 'incorrect' ? <ThumbsDown/> : null}{r.label}</button>)}</fieldset></div>}</section>;
}
