import { ArrowRight, CheckCircle2, Home, RefreshCw, Target, Trophy, XCircle } from 'lucide-react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { topics, useApp } from '../app/AppContext';
import { incorrectKeys, summarize } from '../domain/statistics';
export function ResultsPage() { const { state, setSession } = useApp(); const navigate = useNavigate(); const session = state.session; if (!session || session.status !== 'completed') return <Navigate to="/" replace/>; const summary = summarize(session, topics); const errors = incorrectKeys(session); const percent = summary.mcqTotal ? Math.round(summary.mcqCorrect / summary.mcqTotal * 100) : 0;
  const retry = () => { if (!errors.length) return; setSession({ ...session, id: crypto.randomUUID(), queue: errors, position: 0, cycle: 1, answers: {}, draft: '', status: 'active', startedAt: new Date().toISOString(), completedAt: undefined, requestedSize: 'all' }); navigate('/session'); };
  return <div className="page results-page"><section className="result-hero"><span className="trophy"><Trophy/></span><span className="eyebrow">Сессия завершена</span><h1>Отличная работа!</h1><p>Вы прошли {summary.answered} из {summary.total} заданий.</p></section><div className="result-grid"><div className="score-card"><div className="score-ring" style={{ '--score': `${percent * 3.6}deg` } as React.CSSProperties}><span><strong>{summary.mcqTotal ? `${percent}%` : '—'}</strong><small>верных тестов</small></span></div><div className="score-lines"><p><CheckCircle2/> Верных тестов <strong>{summary.mcqCorrect}</strong></p><p><XCircle/> Ошибок в тестах <strong>{summary.mcqTotal - summary.mcqCorrect}</strong></p><p><Target/> Пропущено <strong>{summary.skipped}</strong></p></div></div><div className="open-stats"><h2>Открытые ответы</h2><div><span><strong>{summary.open.correct}</strong><small>правильно</small></span><span><strong>{summary.open.partial}</strong><small>частично</small></span><span><strong>{summary.open.incorrect}</strong><small>неверно</small></span></div></div></div>
    {(Object.keys(summary.topicErrors).length > 0 || Object.keys(summary.conceptErrors).length > 0) && <div className="breakdown"><Breakdown title="Ошибки по темам" data={summary.topicErrors}/><Breakdown title="Ошибки по концепциям" data={summary.conceptErrors}/></div>}
    <div className="result-actions"><button className="button primary" disabled={!errors.length} onClick={retry}><RefreshCw/> Повторить ошибки ({errors.length})</button><Link className="button secondary" to={`/track/${session.trackId}`}>Новая сессия <ArrowRight/></Link><Link className="button ghost" to="/" onClick={() => setSession(null)}><Home/> На главную</Link></div></div>; }
function Breakdown({ title, data }: { title: string; data: Record<string, number> }) { return <section><h2>{title}</h2>{Object.entries(data).sort((a,b) => b[1]-a[1]).slice(0, 8).map(([name, count]) => <div className="breakdown-row" key={name}><span>{name}</span><strong>{count}</strong></div>)}</section>; }
