import { ArrowLeft, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { topics, useApp } from '../app/AppContext';
import { getDisciplines } from '../domain/disciplines';
import { createSession, filterPool, resolveQueueSize } from '../domain/sessionEngine';
import { getTrack } from '../domain/tracks';
import type { SessionSize } from '../domain/types';
const sizes: { value: SessionSize; label: string }[] = [{ value: 10, label: '10' }, { value: 20, label: '20' }, { value: 50, label: '50' }, { value: 'all', label: 'Все' }, { value: 'infinite', label: '∞' }];
export function TrackSetupPage() { const { trackId } = useParams(); const track = getTrack(trackId); const [params] = useSearchParams(); const [topicKey, setTopicKey] = useState(params.get('topic') ?? ''); const [size, setSize] = useState<SessionSize>(10); const [query, setQuery] = useState(''); const { setSession } = useApp(); const navigate = useNavigate();
  const disciplines = useMemo(() => getDisciplines(topics).filter((item) => item.title.toLowerCase().includes(query.toLowerCase())), [query]); if (!track) return <NotFound/>;
  const pool = filterPool(topics, track, topicKey || undefined); const mcq = pool.filter((x) => x.question.type === 'mcq').length; const open = pool.length - mcq; const actual = resolveQueueSize(pool, track, size);
  const start = () => { if (!pool.length) return; setSession(createSession(track, pool, size, topicKey || undefined)); navigate('/session'); };
  return <div className="page narrow"><Link className="back" to="/"><ArrowLeft/> Все режимы</Link><div className="page-header"><span className="eyebrow">Настройка сессии</span><h1>{track.title}</h1><p>{track.description}</p></div><div className="setup-card">{track.topicMode === 'selected' && <section><h2>1. Выберите дисциплину</h2><label className="search compact"><Search/><span className="sr-only">Поиск дисциплины</span><input placeholder="Поиск по названию…" value={query} onChange={(e) => setQuery(e.target.value)}/></label><div className="topic-picker">{disciplines.map((discipline) => { const compatible = discipline.topics.flatMap((topic) => topic.questions).filter((question) => track.allowedQuestionTypes.includes(question.type)).length; return <label className={`topic-choice ${!compatible ? 'unavailable' : ''}`} key={discipline.key}><input type="radio" name="topic" value={discipline.key} checked={topicKey === discipline.key} disabled={!compatible} onChange={() => setTopicKey(discipline.key)}/><span><strong>{discipline.title}</strong><small>{discipline.topics.length} тем · {compatible ? `${compatible} заданий` : 'Нет подходящих заданий'}</small></span></label>; })}</div></section>}
    <section><h2>{track.topicMode === 'selected' ? '2.' : '1.'} Размер сессии</h2><div className="size-picker">{sizes.map((item) => <label key={String(item.value)}><input type="radio" name="size" checked={size === item.value} onChange={() => setSize(item.value)}/><span>{item.label}</span></label>)}</div><p className="hint">В бесконечном режиме после очереди начнётся новый цикл без повторов внутри него.</p></section>
    <div className="pool-summary"><span><strong>{pool.length}</strong> доступно</span><span><strong>{mcq}</strong> тестов</span><span><strong>{open}</strong> открытых</span></div>{track.allowedQuestionTypes.length === 2 && <p className="hint">Состав смешанной сессии: строго 70% тестовых и 30% открытых заданий.</p>}{pool.length > 0 && actual > 0 && actual < (typeof size === 'number' ? size : 0) && <p className="notice">Фактический размер — {actual}: он уменьшен, чтобы сохранить пропорцию 70/30 без повторов.</p>}{track.allowedQuestionTypes.length === 2 && (size === 'all' || size === 'infinite') && actual > 0 && actual < pool.length && <p className="notice">В один цикл войдут {actual} из {pool.length} вопросов — максимальное количество в пропорции 70/30.</p>}{pool.length > 0 && actual === 0 && <p className="error-text">Недостаточно вопросов обоих типов для формирования блока 70/30.</p>}<button className="button primary full" disabled={!actual || (track.topicMode === 'selected' && !topicKey)} onClick={start}>Начать · {actual} заданий</button>{track.topicMode === 'selected' && topicKey && !pool.length && <p className="error-text">В этой дисциплине нет заданий нужного типа.</p>}</div></div>; }
function NotFound() { return <div className="page narrow empty"><h1>Режим не найден</h1><Link to="/">На главную</Link></div>; }
